#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v19
# autospec commit: a62a849
#
# Source0 file verified with key 0xA2C794A986419D8A (tstellar@redhat.com)
#
Name     : llvm18
Version  : 18.1.8
Release  : 193
URL      : https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.8/llvm-project-18.1.8.src.tar.xz
Source0  : https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.8/llvm-project-18.1.8.src.tar.xz
Source1  : https://github.com/KhronosGroup/SPIRV-Headers/archive/refs/tags/vulkan-sdk-1.3.290.0.tar.gz
Source2  : https://github.com/KhronosGroup/SPIRV-LLVM-Translator/archive/refs/tags/v18.1.4.tar.gz
Source3  : https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.8/llvm-project-18.1.8.src.tar.xz.sig
Source4  : A2C794A986419D8A.pkey
Summary  : Library requirements of the OpenCL C programming language
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause ISC MIT MPL-2.0 NCSA
Requires: llvm18-bin = %{version}-%{release}
Requires: llvm18-lib = %{version}-%{release}
Requires: llvm18-license = %{version}-%{release}
Requires: llvm18-dev = %{version}-%{release}
BuildRequires : SPIRV-Tools
BuildRequires : Sphinx
BuildRequires : Vulkan-Headers-dev Vulkan-Loader-dev Vulkan-Tools
BuildRequires : Z3-dev
BuildRequires : Z3-dev32
BuildRequires : binutils-dev
BuildRequires : buildreq-cmake
BuildRequires : cmake
BuildRequires : curl-dev
BuildRequires : doxygen
BuildRequires : elfutils-dev
BuildRequires : git
BuildRequires : glibc-dev
BuildRequires : gnupg
BuildRequires : googletest-dev
BuildRequires : libffi-dev
BuildRequires : libffi-dev32
BuildRequires : libstdc++-dev
BuildRequires : libxml2-dev
BuildRequires : libxml2-dev32
BuildRequires : llvm
BuildRequires : llvm-dev
BuildRequires : lua-dev
BuildRequires : ncurses-dev
BuildRequires : ninja
BuildRequires : perl
BuildRequires : pkg-config
BuildRequires : pkgconfig(libedit)
BuildRequires : protobuf-dev
BuildRequires : pypi(pybind11)
BuildRequires : python3-dev
BuildRequires : rsync
BuildRequires : swig
BuildRequires : valgrind-dev
BuildRequires : zlib-dev
BuildRequires : zlib-dev32
Patch1: llvm-0001-Improve-physical-core-count-detection.patch
Patch2: llvm-0002-Allow-one-more-FMA-fusion.patch
Patch3: clang-0001-Detect-Clear-Linux-and-apply-Clear-s-default-linker-.patch
Patch4: clang-0002-Make-Clang-default-to-Westmere-on-Clear-Linux.patch
Patch5: clang-0003-Add-f-instructions-that-GCC-has-that-Clang-must-igno.patch
Patch6: compiler-rt-0001-Reduce-mixing-and-matching-sys-and-linux.patch
Patch7: compiler-rt-0002-Add-missing-header-for-linux.patch

%description
Files in this directory:
o .lldbinit:
An example lldb init file that imports the binutils.py module and adds the
following commands: 'itob' and 'utob'.

%package bin
Summary: bin components for the llvm18 package.
Group: Binaries
Requires: llvm18-license = %{version}-%{release}

%description bin
bin components for the llvm18 package.


%package dev
Summary: dev components for the llvm18 package.
Group: Development
Requires: llvm18-lib = %{version}-%{release}
Requires: llvm18-bin = %{version}-%{release}
Provides: llvm18-devel = %{version}-%{release}
Requires: llvm18 = %{version}-%{release}

%description dev
dev components for the llvm18 package.


%package lib
Summary: lib components for the llvm18 package.
Group: Libraries
Requires: llvm18-license = %{version}-%{release}

%description lib
lib components for the llvm18 package.


%package license
Summary: license components for the llvm18 package.
Group: Default

%description license
license components for the llvm18 package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE4}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE3} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) A2C794A986419D8A' gpg.status
%setup -q -n llvm-project-18.1.8.src
cd %{_builddir}
tar xf %{_sourcedir}/v18.1.4.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/vulkan-sdk-1.3.290.0.tar.gz
cd %{_builddir}/llvm-project-18.1.8.src
mkdir -p llvm/projects/SPIRV-LLVM-Translator
cp -r %{_builddir}/SPIRV-LLVM-Translator-18.1.4/* %{_builddir}/llvm-project-18.1.8.src/llvm/projects/SPIRV-LLVM-Translator
mkdir -p llvm/projects/SPIRV-Headers
cp -r %{_builddir}/SPIRV-Headers-vulkan-sdk-1.3.290.0/* %{_builddir}/llvm-project-18.1.8.src/llvm/projects/SPIRV-Headers
%patch -P 1 -p1
%patch -P 2 -p1
%patch -P 3 -p1
%patch -P 4 -p1
%patch -P 5 -p1
%patch -P 6 -p1
%patch -P 7 -p1

%build
## build_prepend_once content
# Bootstrap Clang and the table generators
# See https://build.opensuse.org/package/view_file/devel:tools:compiler/llvm10/llvm10.spec?expand=1
pushd llvm
mkdir clr-bootstrap-build
pushd clr-bootstrap-build
CFLAGS="`sed -E 's/-Wl,\S+\s//g; s/-Wp,-D_FORTIFY_SOURCE=2//; s/-feliminate-unused-debug-types//' <<<$CFLAGS` -fno-integrated-as"
CXXFLAGS="`sed -E 's/-Wl,\S+\s//g; s/-Wp,-D_FORTIFY_SOURCE=2//; s/-feliminate-unused-debug-types//' <<<$CXXFLAGS` -fno-integrated-as"
%cmake .. \
-G Ninja \
-DCMAKE_BUILD_TYPE=Release \
-DBUILD_SHARED_LIBS:BOOL=OFF \
-DCMAKE_C_COMPILER=clang \
-DCMAKE_C_FLAGS="$CFLAGS -g0" \
-DCMAKE_CXX_COMPILER=clang++ \
-DCMAKE_CXX_FLAGS="$CXXFLAGS -g0" \
-DLLVM_ENABLE_PROJECTS="clang" \
-DLLVM_BUILD_LLVM_DYLIB:BOOL=OFF \
-DLLVM_LINK_LLVM_DYLIB:BOOL=OFF \
-DLLVM_ENABLE_ASSERTIONS=OFF \
-DLLVM_TARGETS_TO_BUILD=Native \
-DCLANG_ENABLE_ARCMT:BOOL=OFF \
-DCLANG_ENABLE_STATIC_ANALYZER:BOOL=OFF \
-DCMAKE_SKIP_RPATH:BOOL=OFF \
-DLLVM_LIBDIR_SUFFIX=64 \
-DLLVM_BINUTILS_INCDIR=/usr/include \
-DLLVM_HOST_TRIPLE="x86_64-generic-linux" \
-DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3
ninja -v
popd
export PATH=/usr/lib64/ccache/bin/:${PWD}/clr-bootstrap-build/bin:${PATH}
export LLVM_AR=${PWD}/clr-bootstrap-build/bin/llvm-ar
export LLVM_RANLIB=${PWD}/clr-bootstrap-build/bin/llvm-ranlib
export LLVM_TABLEGEN=${PWD}/clr-bootstrap-build/bin/llvm-tblgen
export CLANG_TABLEGEN=${PWD}/clr-bootstrap-build/bin/clang-tblgen
popd
## build_prepend_once end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1726627499
unset LD_AS_NEEDED
pushd llvm
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CC=clang
export CXX=clang++
export LD=ld.gold
CLEAR_INTERMEDIATE_CFLAGS=${CLEAR_ORIG_CFLAGS/ -Wa,/ -fno-integrated-as -Wa,}
CLEAR_INTERMEDIATE_CXXFLAGS=${CLEAR_ORIG_CXXFLAGS/ -Wa,/ -fno-integrated-as -Wa,}
CLEAR_INTERMEDIATE_CFLAGS="-O2 -g -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=32 -Wformat -Wformat-security -Wno-error -Wl,-z,max-page-size=0x4000 -march=westmere"
CLEAR_INTERMEDIATE_CXXFLAGS=$CLEAR_INTERMEDIATE_CFLAGS
CLEAR_INTERMEDIATE_FFLAGS="-O2 -g -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=32 -Wno-error -Wl,-z,max-page-size=0x4000 -march=westmere"
CLEAR_INTERMEDIATE_FCFLAGS=$CLEAR_INTERMEDIATE_FFLAGS
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fno-lto "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fno-lto "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fno-lto "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fno-lto "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake .. -G Ninja \
-DCMAKE_C_FLAGS="`sed -E 's/-Wl,\S+\s//g; s/-Wp,-D_FORTIFY_SOURCE=2//' <<<$CFLAGS`" \
-DCMAKE_CXX_FLAGS="`sed -E 's/-Wl,\S+\s//g; s/-Wp,-D_FORTIFY_SOURCE=2//' <<<$CXXFLAGS`" \
-DCMAKE_EXE_LINKER_FLAGS="$CXXFLAGS -Wl,--as-needed -Wl,--build-id=sha1" \
-DCMAKE_MODULE_LINKER_FLAGS="$CXXFLAGS -Wl,--as-needed -Wl,--build-id=sha1" \
-DCMAKE_SHARED_LINKER_FLAGS="$CXXFLAGS -Wl,--as-needed -Wl,--build-id=sha1" \
-DENABLE_LINKER_BUILD_ID=ON \
-DCLANG_DEFAULT_PIE_ON_LINUX=ON \
-DBUILD_SHARED_LIBS:BOOL=OFF \
-DLLVM_LINK_LLVM_DYLIB:BOOL=ON \
-DCLANG_LINK_CLANG_DYLIB:BOOL=ON \
-DLLVM_BUILD_RUNTIME:BOOL=ON \
-DLLVM_BUILD_TOOLS:BOOL=ON \
-DLLVM_ENABLE_FFI:BOOL=ON -DFFI_INCLUDE_DIR=`pkg-config --variable=includedir libffi` \
-DLLVM_ENABLE_RTTI:BOOL=ON \
-DLLVM_ENABLE_ZLIB:BOOL=ON \
-DLLVM_REQUIRES_RTTI:BOOL=ON \
-DLLVM_TABLEGEN=$LLVM_TABLEGEN \
-DCLANG_TABLEGEN=$CLANG_TABLEGEN \
-DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra" \
-DLLVM_LIBDIR_SUFFIX=64 \
-DLLVM_BINUTILS_INCDIR=/usr/include \
-DLLVM_HOST_TRIPLE="x86_64-generic-linux" \
-DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3  -G Ninja
ninja  %{?_smp_mflags}
popd
popd

%install
export GCC_IGNORE_WERROR=1
export CC=clang
export CXX=clang++
export LD=ld.gold
CLEAR_INTERMEDIATE_CFLAGS=${CLEAR_ORIG_CFLAGS/ -Wa,/ -fno-integrated-as -Wa,}
CLEAR_INTERMEDIATE_CXXFLAGS=${CLEAR_ORIG_CXXFLAGS/ -Wa,/ -fno-integrated-as -Wa,}
CLEAR_INTERMEDIATE_CFLAGS="-O2 -g -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=32 -Wformat -Wformat-security -Wno-error -Wl,-z,max-page-size=0x4000 -march=westmere"
CLEAR_INTERMEDIATE_CXXFLAGS=$CLEAR_INTERMEDIATE_CFLAGS
CLEAR_INTERMEDIATE_FFLAGS="-O2 -g -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=32 -Wno-error -Wl,-z,max-page-size=0x4000 -march=westmere"
CLEAR_INTERMEDIATE_FCFLAGS=$CLEAR_INTERMEDIATE_FFLAGS
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fno-lto "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fno-lto "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fno-lto "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fno-lto "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1726627499
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/llvm18
cp %{_builddir}/SPIRV-Headers-vulkan-sdk-1.3.290.0/LICENSE %{buildroot}/usr/share/package-licenses/llvm18/438253baaf6fa525f43a0afff2da8be3d7442b75 || :
cp %{_builddir}/SPIRV-LLVM-Translator-18.1.4/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm18/8f178caf2a2d6e6c711a30da69077572df356cf6 || :
cp %{_builddir}/llvm-project-%{version}.src/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm18/af07f365643f841c69797e9059b66f0bd847f1cd || :
cp %{_builddir}/llvm-project-%{version}.src/bolt/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm18/af07f365643f841c69797e9059b66f0bd847f1cd || :
cp %{_builddir}/llvm-project-%{version}.src/clang-tools-extra/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm18/a1691103171dc1d21cfa85f1d4809a16b9f1367f || :
cp %{_builddir}/llvm-project-%{version}.src/clang/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm18/a1691103171dc1d21cfa85f1d4809a16b9f1367f || :
cp %{_builddir}/llvm-project-%{version}.src/clang/tools/clang-format-vs/ClangFormat/license.txt %{buildroot}/usr/share/package-licenses/llvm18/b5d4ab4d1191e592c03310adfbe90d99a46bf9d7 || :
cp %{_builddir}/llvm-project-%{version}.src/compiler-rt/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm18/f4359b9da55a3b9e4d9513eb79cacf125fb49e7b || :
cp %{_builddir}/llvm-project-%{version}.src/cross-project-tests/debuginfo-tests/dexter/LICENSE.txt %{buildroot}/usr/share/package-licenses/llvm18/af07f365643f841c69797e9059b66f0bd847f1cd || :
cp %{_builddir}/llvm-project-%{version}.src/flang/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm18/85c0f2884378413881b4d3e27fc24b220f71889b || :
cp %{_builddir}/llvm-project-%{version}.src/libc/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm18/a1691103171dc1d21cfa85f1d4809a16b9f1367f || :
cp %{_builddir}/llvm-project-%{version}.src/libclc/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm18/8737af83de0d40386dca9a4abe2b6faa83cb4750 || :
cp %{_builddir}/llvm-project-%{version}.src/libcxx/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm18/7b75a5471af8b3d49e60df0a5d72f95ea8214231 || :
cp %{_builddir}/llvm-project-%{version}.src/libcxxabi/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm18/11156021d878bfcbdf2563b4f65db32b4d9f92a3 || :
cp %{_builddir}/llvm-project-%{version}.src/libunwind/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm18/d79062af10a33188d4a74d976323845a2cf9023d || :
cp %{_builddir}/llvm-project-%{version}.src/lld/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm18/6b655b0685aa7ee33fa1e02103b3bf22ed06e099 || :
cp %{_builddir}/llvm-project-%{version}.src/lldb/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm18/8af372ad1edbed2cfaf0e79d25f7136ec6e55b47 || :
cp %{_builddir}/llvm-project-%{version}.src/lldb/third_party/Python/module/pexpect-4.6/LICENSE %{buildroot}/usr/share/package-licenses/llvm18/5a99e7077ee89ba92fb3f584855e8970096cd5dc || :
cp %{_builddir}/llvm-project-%{version}.src/lldb/third_party/Python/module/ptyprocess-0.6.0/LICENSE %{buildroot}/usr/share/package-licenses/llvm18/db1f866b29c6a191752c7c5924b7572cdbc47c34 || :
cp %{_builddir}/llvm-project-%{version}.src/lldb/tools/lldb-dap/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm18/85c0f2884378413881b4d3e27fc24b220f71889b || :
cp %{_builddir}/llvm-project-%{version}.src/llvm/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm18/af07f365643f841c69797e9059b66f0bd847f1cd || :
cp %{_builddir}/llvm-project-%{version}.src/llvm/include/llvm/Support/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm18/5feeec1755c1a12a9ade79c0db7ce0dd05baf119 || :
cp %{_builddir}/llvm-project-%{version}.src/llvm/lib/Support/BLAKE3/LICENSE %{buildroot}/usr/share/package-licenses/llvm18/bfc2b026231b7aca6db90de3471e76dbb94e9c24 || :
cp %{_builddir}/llvm-project-%{version}.src/llvm/test/YAMLParser/LICENSE.txt %{buildroot}/usr/share/package-licenses/llvm18/c01c212bdf3925189f673e2081b44094023860ea || :
cp %{_builddir}/llvm-project-%{version}.src/llvm/utils/lit/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm18/af07f365643f841c69797e9059b66f0bd847f1cd || :
cp %{_builddir}/llvm-project-%{version}.src/mlir/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm18/85c0f2884378413881b4d3e27fc24b220f71889b || :
cp %{_builddir}/llvm-project-%{version}.src/openmp/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm18/e3cccabb67bd491a643d32a7d2b65b49836e626d || :
cp %{_builddir}/llvm-project-%{version}.src/openmp/runtime/src/thirdparty/ittnotify/LICENSE.txt %{buildroot}/usr/share/package-licenses/llvm18/59a8ba331dede4d94bd654ac645e8d27463662f4 || :
cp %{_builddir}/llvm-project-%{version}.src/polly/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm18/8d3b142938f83e7045951089b52676a5605eee37 || :
cp %{_builddir}/llvm-project-%{version}.src/polly/lib/External/isl/LICENSE %{buildroot}/usr/share/package-licenses/llvm18/45c2429b5881295597e96c81fc50f7b8a42e769f || :
cp %{_builddir}/llvm-project-%{version}.src/polly/lib/External/isl/imath/LICENSE %{buildroot}/usr/share/package-licenses/llvm18/385649e7c18da3a07cfbd6679eebd0bca1c698c9 || :
cp %{_builddir}/llvm-project-%{version}.src/pstl/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm18/72c865be698cefc46549ed61e279f98432364fca || :
cp %{_builddir}/llvm-project-%{version}.src/third-party/benchmark/LICENSE %{buildroot}/usr/share/package-licenses/llvm18/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/llvm-project-%{version}.src/third-party/unittest/googlemock/LICENSE.txt %{buildroot}/usr/share/package-licenses/llvm18/5a2314153eadadc69258a9429104cd11804ea304 || :
cp %{_builddir}/llvm-project-%{version}.src/third-party/unittest/googletest/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm18/5a2314153eadadc69258a9429104cd11804ea304 || :
export GOAMD64=v2
pushd llvm
GOAMD64=v2
pushd clr-build
%ninja_install
popd
popd
## Remove excluded files
rm -f %{buildroot}*/usr/lib64/libgomp.so
rm -f %{buildroot}*/usr/lib64/TestPlugin.so
rm -f %{buildroot}*/usr/lib64/cmake/llvm/LLVMStaticExports.cmake
rm -f %{buildroot}*/usr/lib64/cmake/llvm/LLVMStaticExports-relwithdebinfo.cmake
rm -f %{buildroot}*/usr/lib64/pkgconfig/'32*.pc'
rm -f %{buildroot}*/usr/lib/python3.11/site-packages/six.py
rm -f %{buildroot}*/usr/lib64/libclang.so.13
rm -f %{buildroot}*/usr/lib32/libclang.so.13
rm -f %{buildroot}*/usr/lib64/clang/14.0.4/lib/linux/*-i386.so
## install_append content
# Rename the Gold plugin elsewhere, as we're erasing *.so below
mv %{buildroot}/usr/lib64/LLVMgold.so %{buildroot}/usr/lib64/LLVMgold.so.save

# Rename libLLVM (and symlink) elsewhere as we are erasing *.so below
mkdir -p %{buildroot}/tmp/libllvm
mv %{buildroot}/usr/lib64/libLLVM-[0-9]*.so %{buildroot}/tmp/libllvm

# Remove files that should come from the main llvm package
rm -rf %{buildroot}/usr/include
rm -fr %{buildroot}/usr/lib/python3.*
rm -fr %{buildroot}/usr/lib64/libear
rm -fr %{buildroot}/usr/lib64/libscanbuild
rm -rf %{buildroot}/usr/lib64/*.a
rm -rf %{buildroot}/usr/lib64/*.so
rm -rf %{buildroot}/usr/lib64/cmake
rm -rf %{buildroot}/usr/lib64/pkgconfig
rm -rf %{buildroot}/usr/libexec

mv %{buildroot}/usr/share/package-licenses %{buildroot}/usr/
rm -rf %{buildroot}/usr/share/*
mv %{buildroot}/usr/package-licenses %{buildroot}/usr/share

# Rename the tools to have a versioned suffix and symlink back
pushd %{buildroot}/usr
FULL_VERSION=%{version}
VERSION=${FULL_VERSION%%%%.*}
mkdir -p lib64/clang/$FULL_VERSION/bin
mv bin/* lib64/clang/$FULL_VERSION/bin
for f in lib64/clang/$FULL_VERSION/bin/*; do
case "$f" in
*-$VERSION)
# Already versioned, leave it alone
continue
;;
esac
ln -s ../$f bin/${f##*/}-$VERSION
done

# libclang-cpp auto-relocates, so create a symlink so it finds its files
ln -s ../.. lib64/clang/$FULL_VERSION/lib64

# Put the LLVM gold plugin back, under the versioned name
mv lib64/LLVMgold.so.save lib64/LLVMgold-$VERSION.so

# Put libLLVM back
mv %{buildroot}/tmp/libllvm/* %{buildroot}/usr/lib64/

mkdir -p lib/bfd-plugins
ln -s ../../lib64/LLVMgold-$VERSION.so lib/bfd-plugins
popd
## install_append end

%files
%defattr(-,root,root,-)
/usr/lib64/clang/18.1.8/bin/amdgpu-arch
/usr/lib64/clang/18.1.8/bin/analyze-build
/usr/lib64/clang/18.1.8/bin/bugpoint
/usr/lib64/clang/18.1.8/bin/c-index-test
/usr/lib64/clang/18.1.8/bin/clang
/usr/lib64/clang/18.1.8/bin/clang++
/usr/lib64/clang/18.1.8/bin/clang-18
/usr/lib64/clang/18.1.8/bin/clang-apply-replacements
/usr/lib64/clang/18.1.8/bin/clang-change-namespace
/usr/lib64/clang/18.1.8/bin/clang-check
/usr/lib64/clang/18.1.8/bin/clang-cl
/usr/lib64/clang/18.1.8/bin/clang-cpp
/usr/lib64/clang/18.1.8/bin/clang-doc
/usr/lib64/clang/18.1.8/bin/clang-extdef-mapping
/usr/lib64/clang/18.1.8/bin/clang-format
/usr/lib64/clang/18.1.8/bin/clang-include-cleaner
/usr/lib64/clang/18.1.8/bin/clang-include-fixer
/usr/lib64/clang/18.1.8/bin/clang-linker-wrapper
/usr/lib64/clang/18.1.8/bin/clang-move
/usr/lib64/clang/18.1.8/bin/clang-offload-bundler
/usr/lib64/clang/18.1.8/bin/clang-offload-packager
/usr/lib64/clang/18.1.8/bin/clang-pseudo
/usr/lib64/clang/18.1.8/bin/clang-query
/usr/lib64/clang/18.1.8/bin/clang-refactor
/usr/lib64/clang/18.1.8/bin/clang-rename
/usr/lib64/clang/18.1.8/bin/clang-reorder-fields
/usr/lib64/clang/18.1.8/bin/clang-repl
/usr/lib64/clang/18.1.8/bin/clang-scan-deps
/usr/lib64/clang/18.1.8/bin/clang-tblgen
/usr/lib64/clang/18.1.8/bin/clang-tidy
/usr/lib64/clang/18.1.8/bin/clangd
/usr/lib64/clang/18.1.8/bin/diagtool
/usr/lib64/clang/18.1.8/bin/dsymutil
/usr/lib64/clang/18.1.8/bin/find-all-symbols
/usr/lib64/clang/18.1.8/bin/git-clang-format
/usr/lib64/clang/18.1.8/bin/hmaptool
/usr/lib64/clang/18.1.8/bin/intercept-build
/usr/lib64/clang/18.1.8/bin/llc
/usr/lib64/clang/18.1.8/bin/lli
/usr/lib64/clang/18.1.8/bin/llvm-addr2line
/usr/lib64/clang/18.1.8/bin/llvm-ar
/usr/lib64/clang/18.1.8/bin/llvm-as
/usr/lib64/clang/18.1.8/bin/llvm-bcanalyzer
/usr/lib64/clang/18.1.8/bin/llvm-bitcode-strip
/usr/lib64/clang/18.1.8/bin/llvm-c-test
/usr/lib64/clang/18.1.8/bin/llvm-cat
/usr/lib64/clang/18.1.8/bin/llvm-cfi-verify
/usr/lib64/clang/18.1.8/bin/llvm-config
/usr/lib64/clang/18.1.8/bin/llvm-cov
/usr/lib64/clang/18.1.8/bin/llvm-cvtres
/usr/lib64/clang/18.1.8/bin/llvm-cxxdump
/usr/lib64/clang/18.1.8/bin/llvm-cxxfilt
/usr/lib64/clang/18.1.8/bin/llvm-cxxmap
/usr/lib64/clang/18.1.8/bin/llvm-debuginfo-analyzer
/usr/lib64/clang/18.1.8/bin/llvm-debuginfod
/usr/lib64/clang/18.1.8/bin/llvm-debuginfod-find
/usr/lib64/clang/18.1.8/bin/llvm-diff
/usr/lib64/clang/18.1.8/bin/llvm-dis
/usr/lib64/clang/18.1.8/bin/llvm-dlltool
/usr/lib64/clang/18.1.8/bin/llvm-dwarfdump
/usr/lib64/clang/18.1.8/bin/llvm-dwarfutil
/usr/lib64/clang/18.1.8/bin/llvm-dwp
/usr/lib64/clang/18.1.8/bin/llvm-exegesis
/usr/lib64/clang/18.1.8/bin/llvm-extract
/usr/lib64/clang/18.1.8/bin/llvm-gsymutil
/usr/lib64/clang/18.1.8/bin/llvm-ifs
/usr/lib64/clang/18.1.8/bin/llvm-install-name-tool
/usr/lib64/clang/18.1.8/bin/llvm-jitlink
/usr/lib64/clang/18.1.8/bin/llvm-lib
/usr/lib64/clang/18.1.8/bin/llvm-libtool-darwin
/usr/lib64/clang/18.1.8/bin/llvm-link
/usr/lib64/clang/18.1.8/bin/llvm-lipo
/usr/lib64/clang/18.1.8/bin/llvm-lto
/usr/lib64/clang/18.1.8/bin/llvm-lto2
/usr/lib64/clang/18.1.8/bin/llvm-mc
/usr/lib64/clang/18.1.8/bin/llvm-mca
/usr/lib64/clang/18.1.8/bin/llvm-ml
/usr/lib64/clang/18.1.8/bin/llvm-modextract
/usr/lib64/clang/18.1.8/bin/llvm-mt
/usr/lib64/clang/18.1.8/bin/llvm-nm
/usr/lib64/clang/18.1.8/bin/llvm-objcopy
/usr/lib64/clang/18.1.8/bin/llvm-objdump
/usr/lib64/clang/18.1.8/bin/llvm-opt-report
/usr/lib64/clang/18.1.8/bin/llvm-otool
/usr/lib64/clang/18.1.8/bin/llvm-pdbutil
/usr/lib64/clang/18.1.8/bin/llvm-profdata
/usr/lib64/clang/18.1.8/bin/llvm-profgen
/usr/lib64/clang/18.1.8/bin/llvm-ranlib
/usr/lib64/clang/18.1.8/bin/llvm-rc
/usr/lib64/clang/18.1.8/bin/llvm-readelf
/usr/lib64/clang/18.1.8/bin/llvm-readobj
/usr/lib64/clang/18.1.8/bin/llvm-readtapi
/usr/lib64/clang/18.1.8/bin/llvm-reduce
/usr/lib64/clang/18.1.8/bin/llvm-remarkutil
/usr/lib64/clang/18.1.8/bin/llvm-rtdyld
/usr/lib64/clang/18.1.8/bin/llvm-sim
/usr/lib64/clang/18.1.8/bin/llvm-size
/usr/lib64/clang/18.1.8/bin/llvm-spirv
/usr/lib64/clang/18.1.8/bin/llvm-split
/usr/lib64/clang/18.1.8/bin/llvm-stress
/usr/lib64/clang/18.1.8/bin/llvm-strings
/usr/lib64/clang/18.1.8/bin/llvm-strip
/usr/lib64/clang/18.1.8/bin/llvm-symbolizer
/usr/lib64/clang/18.1.8/bin/llvm-tblgen
/usr/lib64/clang/18.1.8/bin/llvm-tli-checker
/usr/lib64/clang/18.1.8/bin/llvm-undname
/usr/lib64/clang/18.1.8/bin/llvm-windres
/usr/lib64/clang/18.1.8/bin/llvm-xray
/usr/lib64/clang/18.1.8/bin/modularize
/usr/lib64/clang/18.1.8/bin/nvptx-arch
/usr/lib64/clang/18.1.8/bin/opt
/usr/lib64/clang/18.1.8/bin/pp-trace
/usr/lib64/clang/18.1.8/bin/run-clang-tidy
/usr/lib64/clang/18.1.8/bin/sancov
/usr/lib64/clang/18.1.8/bin/sanstats
/usr/lib64/clang/18.1.8/bin/scan-build
/usr/lib64/clang/18.1.8/bin/scan-build-py
/usr/lib64/clang/18.1.8/bin/scan-view
/usr/lib64/clang/18.1.8/bin/verify-uselistorder
/usr/lib64/clang/18.1.8/lib64
/usr/lib64/clang/18/include/cuda_wrappers/algorithm
/usr/lib64/clang/18/include/cuda_wrappers/bits/basic_string.tcc
/usr/lib64/clang/18/include/cuda_wrappers/cmath
/usr/lib64/clang/18/include/cuda_wrappers/complex
/usr/lib64/clang/18/include/cuda_wrappers/new
/usr/lib64/clang/18/include/module.modulemap
/usr/lib64/clang/18/include/openmp_wrappers/cmath
/usr/lib64/clang/18/include/openmp_wrappers/complex
/usr/lib64/clang/18/include/openmp_wrappers/new

%files bin
%defattr(-,root,root,-)
/usr/bin/amdgpu-arch-18
/usr/bin/analyze-build-18
/usr/bin/bugpoint-18
/usr/bin/c-index-test-18
/usr/bin/clang++-18
/usr/bin/clang-18
/usr/bin/clang-apply-replacements-18
/usr/bin/clang-change-namespace-18
/usr/bin/clang-check-18
/usr/bin/clang-cl-18
/usr/bin/clang-cpp-18
/usr/bin/clang-doc-18
/usr/bin/clang-extdef-mapping-18
/usr/bin/clang-format-18
/usr/bin/clang-include-cleaner-18
/usr/bin/clang-include-fixer-18
/usr/bin/clang-linker-wrapper-18
/usr/bin/clang-move-18
/usr/bin/clang-offload-bundler-18
/usr/bin/clang-offload-packager-18
/usr/bin/clang-pseudo-18
/usr/bin/clang-query-18
/usr/bin/clang-refactor-18
/usr/bin/clang-rename-18
/usr/bin/clang-reorder-fields-18
/usr/bin/clang-repl-18
/usr/bin/clang-scan-deps-18
/usr/bin/clang-tblgen-18
/usr/bin/clang-tidy-18
/usr/bin/clangd-18
/usr/bin/diagtool-18
/usr/bin/dsymutil-18
/usr/bin/find-all-symbols-18
/usr/bin/git-clang-format-18
/usr/bin/hmaptool-18
/usr/bin/intercept-build-18
/usr/bin/llc-18
/usr/bin/lli-18
/usr/bin/llvm-addr2line-18
/usr/bin/llvm-ar-18
/usr/bin/llvm-as-18
/usr/bin/llvm-bcanalyzer-18
/usr/bin/llvm-bitcode-strip-18
/usr/bin/llvm-c-test-18
/usr/bin/llvm-cat-18
/usr/bin/llvm-cfi-verify-18
/usr/bin/llvm-config-18
/usr/bin/llvm-cov-18
/usr/bin/llvm-cvtres-18
/usr/bin/llvm-cxxdump-18
/usr/bin/llvm-cxxfilt-18
/usr/bin/llvm-cxxmap-18
/usr/bin/llvm-debuginfo-analyzer-18
/usr/bin/llvm-debuginfod-18
/usr/bin/llvm-debuginfod-find-18
/usr/bin/llvm-diff-18
/usr/bin/llvm-dis-18
/usr/bin/llvm-dlltool-18
/usr/bin/llvm-dwarfdump-18
/usr/bin/llvm-dwarfutil-18
/usr/bin/llvm-dwp-18
/usr/bin/llvm-exegesis-18
/usr/bin/llvm-extract-18
/usr/bin/llvm-gsymutil-18
/usr/bin/llvm-ifs-18
/usr/bin/llvm-install-name-tool-18
/usr/bin/llvm-jitlink-18
/usr/bin/llvm-lib-18
/usr/bin/llvm-libtool-darwin-18
/usr/bin/llvm-link-18
/usr/bin/llvm-lipo-18
/usr/bin/llvm-lto-18
/usr/bin/llvm-lto2-18
/usr/bin/llvm-mc-18
/usr/bin/llvm-mca-18
/usr/bin/llvm-ml-18
/usr/bin/llvm-modextract-18
/usr/bin/llvm-mt-18
/usr/bin/llvm-nm-18
/usr/bin/llvm-objcopy-18
/usr/bin/llvm-objdump-18
/usr/bin/llvm-opt-report-18
/usr/bin/llvm-otool-18
/usr/bin/llvm-pdbutil-18
/usr/bin/llvm-profdata-18
/usr/bin/llvm-profgen-18
/usr/bin/llvm-ranlib-18
/usr/bin/llvm-rc-18
/usr/bin/llvm-readelf-18
/usr/bin/llvm-readobj-18
/usr/bin/llvm-readtapi-18
/usr/bin/llvm-reduce-18
/usr/bin/llvm-remarkutil-18
/usr/bin/llvm-rtdyld-18
/usr/bin/llvm-sim-18
/usr/bin/llvm-size-18
/usr/bin/llvm-spirv-18
/usr/bin/llvm-split-18
/usr/bin/llvm-stress-18
/usr/bin/llvm-strings-18
/usr/bin/llvm-strip-18
/usr/bin/llvm-symbolizer-18
/usr/bin/llvm-tblgen-18
/usr/bin/llvm-tli-checker-18
/usr/bin/llvm-undname-18
/usr/bin/llvm-windres-18
/usr/bin/llvm-xray-18
/usr/bin/modularize-18
/usr/bin/nvptx-arch-18
/usr/bin/opt-18
/usr/bin/pp-trace-18
/usr/bin/run-clang-tidy-18
/usr/bin/sancov-18
/usr/bin/sanstats-18
/usr/bin/scan-build-18
/usr/bin/scan-build-py-18
/usr/bin/scan-view-18
/usr/bin/verify-uselistorder-18

%files dev
%defattr(-,root,root,-)
/usr/lib64/clang/18/include/__clang_cuda_builtin_vars.h
/usr/lib64/clang/18/include/__clang_cuda_cmath.h
/usr/lib64/clang/18/include/__clang_cuda_complex_builtins.h
/usr/lib64/clang/18/include/__clang_cuda_device_functions.h
/usr/lib64/clang/18/include/__clang_cuda_intrinsics.h
/usr/lib64/clang/18/include/__clang_cuda_libdevice_declares.h
/usr/lib64/clang/18/include/__clang_cuda_math.h
/usr/lib64/clang/18/include/__clang_cuda_math_forward_declares.h
/usr/lib64/clang/18/include/__clang_cuda_runtime_wrapper.h
/usr/lib64/clang/18/include/__clang_cuda_texture_intrinsics.h
/usr/lib64/clang/18/include/__clang_hip_cmath.h
/usr/lib64/clang/18/include/__clang_hip_libdevice_declares.h
/usr/lib64/clang/18/include/__clang_hip_math.h
/usr/lib64/clang/18/include/__clang_hip_runtime_wrapper.h
/usr/lib64/clang/18/include/__clang_hip_stdlib.h
/usr/lib64/clang/18/include/__stdarg___gnuc_va_list.h
/usr/lib64/clang/18/include/__stdarg___va_copy.h
/usr/lib64/clang/18/include/__stdarg_va_arg.h
/usr/lib64/clang/18/include/__stdarg_va_copy.h
/usr/lib64/clang/18/include/__stdarg_va_list.h
/usr/lib64/clang/18/include/__stddef_max_align_t.h
/usr/lib64/clang/18/include/__stddef_null.h
/usr/lib64/clang/18/include/__stddef_nullptr_t.h
/usr/lib64/clang/18/include/__stddef_offsetof.h
/usr/lib64/clang/18/include/__stddef_ptrdiff_t.h
/usr/lib64/clang/18/include/__stddef_rsize_t.h
/usr/lib64/clang/18/include/__stddef_size_t.h
/usr/lib64/clang/18/include/__stddef_unreachable.h
/usr/lib64/clang/18/include/__stddef_wchar_t.h
/usr/lib64/clang/18/include/__stddef_wint_t.h
/usr/lib64/clang/18/include/__wmmintrin_aes.h
/usr/lib64/clang/18/include/__wmmintrin_pclmul.h
/usr/lib64/clang/18/include/adcintrin.h
/usr/lib64/clang/18/include/adxintrin.h
/usr/lib64/clang/18/include/altivec.h
/usr/lib64/clang/18/include/ammintrin.h
/usr/lib64/clang/18/include/amxcomplexintrin.h
/usr/lib64/clang/18/include/amxfp16intrin.h
/usr/lib64/clang/18/include/amxintrin.h
/usr/lib64/clang/18/include/arm64intr.h
/usr/lib64/clang/18/include/arm_acle.h
/usr/lib64/clang/18/include/arm_bf16.h
/usr/lib64/clang/18/include/arm_cde.h
/usr/lib64/clang/18/include/arm_cmse.h
/usr/lib64/clang/18/include/arm_fp16.h
/usr/lib64/clang/18/include/arm_mve.h
/usr/lib64/clang/18/include/arm_neon.h
/usr/lib64/clang/18/include/arm_neon_sve_bridge.h
/usr/lib64/clang/18/include/arm_sme.h
/usr/lib64/clang/18/include/arm_sve.h
/usr/lib64/clang/18/include/arm_vector_types.h
/usr/lib64/clang/18/include/armintr.h
/usr/lib64/clang/18/include/avx2intrin.h
/usr/lib64/clang/18/include/avx512bf16intrin.h
/usr/lib64/clang/18/include/avx512bitalgintrin.h
/usr/lib64/clang/18/include/avx512bwintrin.h
/usr/lib64/clang/18/include/avx512cdintrin.h
/usr/lib64/clang/18/include/avx512dqintrin.h
/usr/lib64/clang/18/include/avx512erintrin.h
/usr/lib64/clang/18/include/avx512fintrin.h
/usr/lib64/clang/18/include/avx512fp16intrin.h
/usr/lib64/clang/18/include/avx512ifmaintrin.h
/usr/lib64/clang/18/include/avx512ifmavlintrin.h
/usr/lib64/clang/18/include/avx512pfintrin.h
/usr/lib64/clang/18/include/avx512vbmi2intrin.h
/usr/lib64/clang/18/include/avx512vbmiintrin.h
/usr/lib64/clang/18/include/avx512vbmivlintrin.h
/usr/lib64/clang/18/include/avx512vlbf16intrin.h
/usr/lib64/clang/18/include/avx512vlbitalgintrin.h
/usr/lib64/clang/18/include/avx512vlbwintrin.h
/usr/lib64/clang/18/include/avx512vlcdintrin.h
/usr/lib64/clang/18/include/avx512vldqintrin.h
/usr/lib64/clang/18/include/avx512vlfp16intrin.h
/usr/lib64/clang/18/include/avx512vlintrin.h
/usr/lib64/clang/18/include/avx512vlvbmi2intrin.h
/usr/lib64/clang/18/include/avx512vlvnniintrin.h
/usr/lib64/clang/18/include/avx512vlvp2intersectintrin.h
/usr/lib64/clang/18/include/avx512vnniintrin.h
/usr/lib64/clang/18/include/avx512vp2intersectintrin.h
/usr/lib64/clang/18/include/avx512vpopcntdqintrin.h
/usr/lib64/clang/18/include/avx512vpopcntdqvlintrin.h
/usr/lib64/clang/18/include/avxifmaintrin.h
/usr/lib64/clang/18/include/avxintrin.h
/usr/lib64/clang/18/include/avxneconvertintrin.h
/usr/lib64/clang/18/include/avxvnniint16intrin.h
/usr/lib64/clang/18/include/avxvnniint8intrin.h
/usr/lib64/clang/18/include/avxvnniintrin.h
/usr/lib64/clang/18/include/bmi2intrin.h
/usr/lib64/clang/18/include/bmiintrin.h
/usr/lib64/clang/18/include/builtins.h
/usr/lib64/clang/18/include/cet.h
/usr/lib64/clang/18/include/cetintrin.h
/usr/lib64/clang/18/include/cldemoteintrin.h
/usr/lib64/clang/18/include/clflushoptintrin.h
/usr/lib64/clang/18/include/clwbintrin.h
/usr/lib64/clang/18/include/clzerointrin.h
/usr/lib64/clang/18/include/cmpccxaddintrin.h
/usr/lib64/clang/18/include/cpuid.h
/usr/lib64/clang/18/include/crc32intrin.h
/usr/lib64/clang/18/include/cuda_wrappers/bits/basic_string.h
/usr/lib64/clang/18/include/cuda_wrappers/bits/shared_ptr_base.h
/usr/lib64/clang/18/include/emmintrin.h
/usr/lib64/clang/18/include/enqcmdintrin.h
/usr/lib64/clang/18/include/f16cintrin.h
/usr/lib64/clang/18/include/float.h
/usr/lib64/clang/18/include/fma4intrin.h
/usr/lib64/clang/18/include/fmaintrin.h
/usr/lib64/clang/18/include/fxsrintrin.h
/usr/lib64/clang/18/include/gfniintrin.h
/usr/lib64/clang/18/include/hexagon_circ_brev_intrinsics.h
/usr/lib64/clang/18/include/hexagon_protos.h
/usr/lib64/clang/18/include/hexagon_types.h
/usr/lib64/clang/18/include/hresetintrin.h
/usr/lib64/clang/18/include/htmintrin.h
/usr/lib64/clang/18/include/htmxlintrin.h
/usr/lib64/clang/18/include/hvx_hexagon_protos.h
/usr/lib64/clang/18/include/ia32intrin.h
/usr/lib64/clang/18/include/immintrin.h
/usr/lib64/clang/18/include/intrin.h
/usr/lib64/clang/18/include/inttypes.h
/usr/lib64/clang/18/include/invpcidintrin.h
/usr/lib64/clang/18/include/iso646.h
/usr/lib64/clang/18/include/keylockerintrin.h
/usr/lib64/clang/18/include/larchintrin.h
/usr/lib64/clang/18/include/lasxintrin.h
/usr/lib64/clang/18/include/limits.h
/usr/lib64/clang/18/include/llvm_libc_wrappers/assert.h
/usr/lib64/clang/18/include/llvm_libc_wrappers/ctype.h
/usr/lib64/clang/18/include/llvm_libc_wrappers/inttypes.h
/usr/lib64/clang/18/include/llvm_libc_wrappers/stdio.h
/usr/lib64/clang/18/include/llvm_libc_wrappers/stdlib.h
/usr/lib64/clang/18/include/llvm_libc_wrappers/string.h
/usr/lib64/clang/18/include/llvm_libc_wrappers/time.h
/usr/lib64/clang/18/include/lsxintrin.h
/usr/lib64/clang/18/include/lwpintrin.h
/usr/lib64/clang/18/include/lzcntintrin.h
/usr/lib64/clang/18/include/mm3dnow.h
/usr/lib64/clang/18/include/mm_malloc.h
/usr/lib64/clang/18/include/mmintrin.h
/usr/lib64/clang/18/include/movdirintrin.h
/usr/lib64/clang/18/include/msa.h
/usr/lib64/clang/18/include/mwaitxintrin.h
/usr/lib64/clang/18/include/nmmintrin.h
/usr/lib64/clang/18/include/opencl-c-base.h
/usr/lib64/clang/18/include/opencl-c.h
/usr/lib64/clang/18/include/openmp_wrappers/__clang_openmp_device_functions.h
/usr/lib64/clang/18/include/openmp_wrappers/complex.h
/usr/lib64/clang/18/include/openmp_wrappers/complex_cmath.h
/usr/lib64/clang/18/include/openmp_wrappers/math.h
/usr/lib64/clang/18/include/pconfigintrin.h
/usr/lib64/clang/18/include/pkuintrin.h
/usr/lib64/clang/18/include/pmmintrin.h
/usr/lib64/clang/18/include/popcntintrin.h
/usr/lib64/clang/18/include/ppc_wrappers/bmi2intrin.h
/usr/lib64/clang/18/include/ppc_wrappers/bmiintrin.h
/usr/lib64/clang/18/include/ppc_wrappers/emmintrin.h
/usr/lib64/clang/18/include/ppc_wrappers/immintrin.h
/usr/lib64/clang/18/include/ppc_wrappers/mm_malloc.h
/usr/lib64/clang/18/include/ppc_wrappers/mmintrin.h
/usr/lib64/clang/18/include/ppc_wrappers/nmmintrin.h
/usr/lib64/clang/18/include/ppc_wrappers/pmmintrin.h
/usr/lib64/clang/18/include/ppc_wrappers/smmintrin.h
/usr/lib64/clang/18/include/ppc_wrappers/tmmintrin.h
/usr/lib64/clang/18/include/ppc_wrappers/x86gprintrin.h
/usr/lib64/clang/18/include/ppc_wrappers/x86intrin.h
/usr/lib64/clang/18/include/ppc_wrappers/xmmintrin.h
/usr/lib64/clang/18/include/prfchiintrin.h
/usr/lib64/clang/18/include/prfchwintrin.h
/usr/lib64/clang/18/include/ptwriteintrin.h
/usr/lib64/clang/18/include/raointintrin.h
/usr/lib64/clang/18/include/rdpruintrin.h
/usr/lib64/clang/18/include/rdseedintrin.h
/usr/lib64/clang/18/include/riscv_bitmanip.h
/usr/lib64/clang/18/include/riscv_crypto.h
/usr/lib64/clang/18/include/riscv_ntlh.h
/usr/lib64/clang/18/include/riscv_vector.h
/usr/lib64/clang/18/include/rtmintrin.h
/usr/lib64/clang/18/include/s390intrin.h
/usr/lib64/clang/18/include/serializeintrin.h
/usr/lib64/clang/18/include/sgxintrin.h
/usr/lib64/clang/18/include/sha512intrin.h
/usr/lib64/clang/18/include/shaintrin.h
/usr/lib64/clang/18/include/sifive_vector.h
/usr/lib64/clang/18/include/sm3intrin.h
/usr/lib64/clang/18/include/sm4intrin.h
/usr/lib64/clang/18/include/smmintrin.h
/usr/lib64/clang/18/include/stdalign.h
/usr/lib64/clang/18/include/stdarg.h
/usr/lib64/clang/18/include/stdatomic.h
/usr/lib64/clang/18/include/stdbool.h
/usr/lib64/clang/18/include/stdckdint.h
/usr/lib64/clang/18/include/stddef.h
/usr/lib64/clang/18/include/stdint.h
/usr/lib64/clang/18/include/stdnoreturn.h
/usr/lib64/clang/18/include/tbmintrin.h
/usr/lib64/clang/18/include/tgmath.h
/usr/lib64/clang/18/include/tmmintrin.h
/usr/lib64/clang/18/include/tsxldtrkintrin.h
/usr/lib64/clang/18/include/uintrintrin.h
/usr/lib64/clang/18/include/unwind.h
/usr/lib64/clang/18/include/usermsrintrin.h
/usr/lib64/clang/18/include/vadefs.h
/usr/lib64/clang/18/include/vaesintrin.h
/usr/lib64/clang/18/include/varargs.h
/usr/lib64/clang/18/include/vecintrin.h
/usr/lib64/clang/18/include/velintrin.h
/usr/lib64/clang/18/include/velintrin_approx.h
/usr/lib64/clang/18/include/velintrin_gen.h
/usr/lib64/clang/18/include/vpclmulqdqintrin.h
/usr/lib64/clang/18/include/waitpkgintrin.h
/usr/lib64/clang/18/include/wasm_simd128.h
/usr/lib64/clang/18/include/wbnoinvdintrin.h
/usr/lib64/clang/18/include/wmmintrin.h
/usr/lib64/clang/18/include/x86gprintrin.h
/usr/lib64/clang/18/include/x86intrin.h
/usr/lib64/clang/18/include/xmmintrin.h
/usr/lib64/clang/18/include/xopintrin.h
/usr/lib64/clang/18/include/xsavecintrin.h
/usr/lib64/clang/18/include/xsaveintrin.h
/usr/lib64/clang/18/include/xsaveoptintrin.h
/usr/lib64/clang/18/include/xsavesintrin.h
/usr/lib64/clang/18/include/xtestintrin.h

%files lib
%defattr(-,root,root,-)
/usr/lib/bfd-plugins/LLVMgold-18.so
/usr/lib64/LLVMgold-18.so
/usr/lib64/libLLVM-18.so
/usr/lib64/libLLVM.so.18.1
/usr/lib64/libLTO.so.18.1
/usr/lib64/libRemarks.so.18.1
/usr/lib64/libclang-cpp.so.18.1
/usr/lib64/libclang.so.18.1
/usr/lib64/libclang.so.18.1.8

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/llvm18/11156021d878bfcbdf2563b4f65db32b4d9f92a3
/usr/share/package-licenses/llvm18/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/llvm18/385649e7c18da3a07cfbd6679eebd0bca1c698c9
/usr/share/package-licenses/llvm18/438253baaf6fa525f43a0afff2da8be3d7442b75
/usr/share/package-licenses/llvm18/45c2429b5881295597e96c81fc50f7b8a42e769f
/usr/share/package-licenses/llvm18/59a8ba331dede4d94bd654ac645e8d27463662f4
/usr/share/package-licenses/llvm18/5a2314153eadadc69258a9429104cd11804ea304
/usr/share/package-licenses/llvm18/5a99e7077ee89ba92fb3f584855e8970096cd5dc
/usr/share/package-licenses/llvm18/5feeec1755c1a12a9ade79c0db7ce0dd05baf119
/usr/share/package-licenses/llvm18/6b655b0685aa7ee33fa1e02103b3bf22ed06e099
/usr/share/package-licenses/llvm18/72c865be698cefc46549ed61e279f98432364fca
/usr/share/package-licenses/llvm18/7b75a5471af8b3d49e60df0a5d72f95ea8214231
/usr/share/package-licenses/llvm18/85c0f2884378413881b4d3e27fc24b220f71889b
/usr/share/package-licenses/llvm18/8737af83de0d40386dca9a4abe2b6faa83cb4750
/usr/share/package-licenses/llvm18/8af372ad1edbed2cfaf0e79d25f7136ec6e55b47
/usr/share/package-licenses/llvm18/8d3b142938f83e7045951089b52676a5605eee37
/usr/share/package-licenses/llvm18/8f178caf2a2d6e6c711a30da69077572df356cf6
/usr/share/package-licenses/llvm18/a1691103171dc1d21cfa85f1d4809a16b9f1367f
/usr/share/package-licenses/llvm18/af07f365643f841c69797e9059b66f0bd847f1cd
/usr/share/package-licenses/llvm18/b5d4ab4d1191e592c03310adfbe90d99a46bf9d7
/usr/share/package-licenses/llvm18/bfc2b026231b7aca6db90de3471e76dbb94e9c24
/usr/share/package-licenses/llvm18/c01c212bdf3925189f673e2081b44094023860ea
/usr/share/package-licenses/llvm18/d79062af10a33188d4a74d976323845a2cf9023d
/usr/share/package-licenses/llvm18/db1f866b29c6a191752c7c5924b7572cdbc47c34
/usr/share/package-licenses/llvm18/e3cccabb67bd491a643d32a7d2b65b49836e626d
/usr/share/package-licenses/llvm18/f4359b9da55a3b9e4d9513eb79cacf125fb49e7b
